# Generated by Django 4.2.1 on 2023-10-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile_no',
            field=models.IntegerField(default=91),
        ),
    ]
