# Generated by Django 4.2.1 on 2023-10-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seller_address_seller_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
