# Generated by Django 4.2.1 on 2023-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile_no',
            field=models.IntegerField(default=91),
        ),
    ]
