# Generated by Django 4.2.1 on 2023-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shippingaddress_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
