# Generated by Django 4.2.1 on 2023-10-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shippingaddress_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_stock',
        ),
    ]
