# Generated by Django 4.2.1 on 2023-10-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
