# Generated by Django 4.2.1 on 2023-10-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_category_slug_productimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
