# Generated by Django 4.2.1 on 2023-10-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_shippingaddress_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
