# Generated by Django 4.2.1 on 2023-10-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_shippingaddress_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='slug',
            field=models.SlugField(default=True, max_length=200),
        ),
    ]
