# Generated by Django 4.2.1 on 2023-10-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_cart_slug_alter_cartitem_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
    ]
