# Generated by Django 4.2.1 on 2023-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_productimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
    ]
