# Generated by Django 4.2.1 on 2023-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_productimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
