# Generated by Django 4.2.1 on 2023-10-18 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_productimage_slug_alter_review_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
