# Generated by Django 4.2.1 on 2023-10-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_productimage_slug_productimage_image_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_slug',
            new_name='slug',
        ),
    ]
