# Generated by Django 4.2.1 on 2023-10-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='slug',
        ),
    ]
