# Generated by Django 4.2.1 on 2023-11-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
