# Generated by Django 4.2.1 on 2024-04-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='api.size'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.style'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ManyToManyField(blank=True, null=True, to='api.style'),
        ),
    ]
